### ISSUE TITLE
[Nougat+] App Installer doesn't open

### ISSUE THREAD

**Issue by ishaangarg** [ezetap/android-payments-sdk#1]
On Nougat and above, the ezetap service app downloads but the app installer doesn't open. I have added the required provider in Manifest, but it doesn't seem to work.

**Comment by ShashankEzetap** [comment]
Hi Ishaan, We need the below info to fix this-
- Is this a Cordova Integration or Native Android Integration
- Do you see any Exceptions in the log? If yes please provide the same.
- Can you check if there's an entry for ezetap-download in provider_paths.xml ?

**Comment by ishaangarg** [comment]
-

**Comment by ishaangarg** [comment]
- Native Android Integration
- No exceptions, just the Downloaded File Path is printed, after that nothing happens.
- provider_paths.xml has both the entries for ezetap-download

Also, when do we get this error: _EZETAP_0000073 Invalid credentials. Verify your credentials, login again, or contact your supervisor._

**Comment by VallurRaghavaReddy** [comment]
Did you create a account in sandbox.ezetap.com?
Which version of SDK are you using?

Please follow below steps mentioned in the README.md
 
We are also keen to understand on what kind of solutions you are trying to build using Ezetap SDK.

**Comment by VallurRaghavaReddy** [comment]
Forgot to mention please go though the documentation at this link https://sandbox.ezetap.com/static/index.html

**Comment by ishaangarg** [comment]
Using v2.3
Upon calling `EzeAPI.prepareDevice()`, the APK downloads at: /ezetap-download/ezetap_android_bservice.apk

But then in Nougat nothing happens, the EzetapActivity remains opened, while below Nougat the App Installer is opened correctly.

**Comment by VallurRaghavaReddy** [comment]
Did you add <provider> in your manifest as mentioned 
 <provider
        android:name="com.ezetap.sdk.EzetapFileProvider"
	    android:authorities="<Your application ID>.EzetapFileProvider"
	    android:exported="false"
	    android:grantUriPermissions="true" >
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_paths" />
	</provider>

**Comment by ishaangarg** [comment]
Yep, this is what my manifest looks like:

        <activity
            android:name="com.eze.api.EzeAPIActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
            android:screenOrientation="portrait"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

        <provider
            android:name="com.ezetap.sdk.EzetapFileProvider"
            android:authorities="in.myDomain.myApp.EzetapFileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>

    </application>

**Comment by VallurRaghavaReddy** [comment]
What is your package?
You can also refer to the sample code available on how use the SDK.
Did you create a account on [sandbox.ezetap.com](sanbox.ezetap.com)?
We are also keen to understand on what kind of solutions you are trying to build using Ezetap SDK.

**Comment by ishaangarg** [comment]
Package is `in.shadowfax.gandalf`

This is how the actual authorities looks like in my manifest
`android:authorities="in.shadowfax.gandalf.EzetapFileProvider"`

I actually am just trying to get the EzeNativeSampleActivity from Github sample app to work in my project.

Yes I did create an account at sandbox.ezetap.com and i'm using the demo key from there and it seems to be working fine.

PS: This is my provider_paths.xml under res/xml
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android" >
    <files-path name="ezetap-download" />
    <external-path name="ezetap-download" />
</paths>
```

FYI: After the apk is downloaded, the EzeAPIActivity remains opened with hidden statusBar.

**Comment by VallurRaghavaReddy** [comment]
Is the sample application working for you?

**Comment by ishaangarg** [comment]
Got the sample app working. So here's the deal:

my app's `targetSdkVersion = 22` and we don't have runtime perms. 
For the sample app `targetSdkVersion = 25` so the runtime perm dialog pops up asking for write access.

I already have `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` permission in my manifest.
I cant bump targetSdkVersion for my app, so what's the workaround?

**Comment by VallurRaghavaReddy** [comment]
Permission should be available for you. I do not think it is permission issue. You have follow all the steps mentioned in including the aar and it should work. Please reverify. 
You just need to follow below steps:
#### If you choose `.aar`:
* Copy the `aar` file, available in the latest version in <a href=https://github.com/ezetap/android-payments-sdk/tree/master/release>release</a> folder, into `libs` folder under your project directory.

* Add the below line in dependencies of your `build.gradle` file in your application.
```
  compile(name: 'ezetapandroidsdk_X', ext: 'aar') Note: 'X' in the 'ezetapandroidsdk_X' represents the version (ex: ezetapandroidsdk_2_0)
``` 

* Add the below line in repositories section of your `build.gradle`
```
  flatDir {
      dirs 'libs'
  }
```

* Add the below provider in your project's `manifest` file inside application tag & replace your application ID in the place of `<Your application ID>`. Your app ID/package name can be found in your app's `manifest` file under package tag or in the `applicationId` tag of your Gradle file.

```xml

    <provider
        android:name="com.ezetap.sdk.EzetapFileProvider"
	    android:authorities="<Your application ID>.EzetapFileProvider"
	    android:exported="false"
	    android:grantUriPermissions="true" >
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_paths" />
	</provider>

```

* If you have set attribute "tools:node" in you manifest for your application node. Please set it as tools:node="merge" as shown below, it is needed to merge all the elements from our manifest.
```
 <application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        tools:node="merge"
        android:supportsRtl="true" >
```

If still not resolved you can share you number and we will call you help you out.

**Comment by ishaangarg** [comment]
haha yay! I got it working. Weird though.

I replaced 
`android:authorities="in.shadowfax.gandalf.EzetapFileProvider"`
with 
`android:authorities="${applicationId}.EzetapFileProvider"`

and voila! App installer is now opening properly.

This is weird though. My build.gradle even says `applicationId "in.shadowfax.gandalf"` so why the hardcoded app id isn't working is beyond me.

I am closing the issue, but please do let me know if you have any idea why hardcoding the app ID might not work. This consumed 2 good days of mine.

**Comment by VallurRaghavaReddy** [comment]
If you have multiple build types and if applicationId is changing accordingly (by a suffix or override)? Then the package name will change accordingly in which case the hard-coding
